CREATE TABLE CITIES
(
	CITYID INT NOT NULL,
	CITYNAME VARCHAR(30),
	STATENAME VARCHAR(30),
	COUNTRY VARCHAR(30) DEFAULT 'INDIA'
);

INSERT INTO CITIES(CITYID,CITYNAME,STATENAME) VALUES(11,'BANGALORE','KARNATAKA')
INSERT INTO CITIES VALUES(11,'AAAAAA','FFFFFFFF','SRILANKA')

SELECT * FROM CITIES;