SELECT * FROM STAFF


SELECT * FROM STAFFCOPY

DELETE FROM STAFFCOPY WHERE STAFFID=114
DELETE FROM STAFFCOPY WHERE STAFFID=333


INSERT INTO STAFFCOPY VALUES(444,'JYOTHI',33,'PROFESSOR',222)
INSERT INTO STAFFCOPY VALUES(666,'PRIYA',44,'ASSOCIATE PROFESSOR',222)


SELECT * FROM STAFF
UNION ALL
SELECT * FROM STAFFCOPY


SELECT * FROM STAFF
UNION 
SELECT * FROM STAFFCOPY



SELECT * FROM STAFF
INTERSECT 
SELECT * FROM STAFFCOPY


CREATE TABLE EXAMPLE1
(
	ID INT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(30)

);
INSERT INTO EXAMPLE1 VALUES('AAA');
INSERT INTO EXAMPLE1 VALUES('BBB');
INSERT INTO EXAMPLE1 VALUES('CCC');
INSERT INTO EXAMPLE1 VALUES('DDD');
INSERT INTO EXAMPLE1 VALUES('EEE');
SELECT * FROM EXAMPLE1;



CREATE TABLE EXAMPLE2
(
	ID INT NOT NULL IDENTITY(10,1),
	NAME VARCHAR(30)

);
INSERT INTO EXAMPLE2 VALUES('AAA');
INSERT INTO EXAMPLE2 VALUES('BBB');
INSERT INTO EXAMPLE2 VALUES('CCC');
SELECT * FROM EXAMPLE2;


CREATE TABLE EXAMPLE3
(
	ID INT NOT NULL IDENTITY(10,5),
	NAME VARCHAR(30)

);
INSERT INTO EXAMPLE3 VALUES('AAA');
INSERT INTO EXAMPLE3 VALUES('BBB');
INSERT INTO EXAMPLE3 VALUES('CCC');
SELECT * FROM EXAMPLE3;


