CREATE TABLE STUDENTINFO
(
	ID INT NOT NULL,
	SNAME VARCHAR(30),
	CID INT NOT NULL,
	MARKS INT
);


SELECT * FROM STUDENT

SELECT * FROM REPORT

SELECT R.ID,S.SNAME,R.CID,R.MARKS INTO STUDENTINFO1
FROM REPORT R, STUDENT S
WHERE R.ID=S.ID AND R.CID = S.CID

SELECT * FROM STUDENTINFO1

--INSERT DATA INTO EXISTING TABLE

SELECT * FROM STUDENTINFO

INSERT INTO STUDENTINFO
SELECT R.ID,S.SNAME,R.CID,R.MARKS
FROM REPORT R, STUDENT S
WHERE R.ID=S.ID AND R.CID = S.CID


SELECT * INTO STAFFCOPY FROM STAFF
SELECT * FROM STAFFCOPY






