select * from student;
select * from course;

--the match before TH and after TH can be anything
select * from COURSE where CNAME like '%TH%'

-- matches anything starts with ja
select * from COURSE where CNAME like 'JA%'


select * from COURSE where CNAME like 'ja%'

--matches from second character it should be sharp, first char can be anything
select * from COURSE where CNAME like '_sharp'


--matches course that has starting letter either c or p
select * from COURSE where CNAME like '[CP]%'


--matches course that does not have starting letter either c or p
select * from COURSE where CNAME not like '[CP]%'





--create table for report->marks of student based on course

CREATE TABLE REPORT
(
	ID INT NOT NULL,
	CID INT NOT NULL,
	MARKS INT
);

INSERT INTO REPORT VALUES(1,11,88);
INSERT INTO REPORT VALUES(1,22,44);
INSERT INTO REPORT VALUES(2,11,77);
INSERT INTO REPORT VALUES(2,22,66);
INSERT INTO REPORT VALUES(3,44,78);
INSERT INTO REPORT VALUES(4,55,90);
INSERT INTO REPORT VALUES(5,33,69);


SELECT * FROM REPORT;

SELECT S.ID,S.SNAME,R.CID,R.MARKS
FROM STUDENT S
INNER JOIN REPORT R
ON S.ID=R.ID AND S.SNAME LIKE '[ACE]%'


SELECT S.ID,S.SNAME,R.CID,C.CNAME,R.MARKS
FROM STUDENT S
INNER JOIN REPORT R
ON S.ID=R.ID 
INNER JOIN COURSE C
ON C.CID=R.CID

SELECT * FROM REPORT

SELECT TOP 5 * FROM REPORT


CREATE TABLE STAFF
(
	STAFFID INT NOT NULL,
	STAFFNAME VARCHAR(30),
	CID INT,
	DESIGNATION VARCHAR(30),
	HOD INT
);
INSERT INTO STAFF VALUES(111,'AKSHATA',11,'PROFESSOR',222);
INSERT INTO STAFF VALUES(112,'SUSHMA',22,'ASSOCIATE PROFESSOR',222);
INSERT INTO STAFF VALUES(113,'BHARATH',33,'ASSOCIATE PROFESSOR',333);
INSERT INTO STAFF VALUES(114,'SANKEERTH',11,'PROFESSOR',333);
INSERT INTO STAFF VALUES(222,'NAGRAJ',44,'PROFESSOR',444);
INSERT INTO STAFF VALUES(333,'KARTHIK',11,'PROFESSOR',222);

SELECT * FROM STAFF;


SELECT E.STAFFID , E.STAFFNAME ,H.STAFFNAME
FROM STAFF E
INNER JOIN STAFF H
ON E.HOD=H.STAFFID
SELECT * FROM STAFF
SELECT * FROM STUDENT

SELECT E.STAFFNAME,S.SNAME
FROM STUDENT S
INNER JOIN STAFF E
ON S.CID = E.CID
WHERE STAFFNAME IN ('SUSHMA','BHARATH')


SELECT E.STAFFNAME,S.SNAME
FROM STUDENT S
INNER JOIN STAFF E
ON S.CID = E.CID
WHERE STAFFNAME ='SUSHMA' OR STAFFNAME='BHARATH'





SELECT E.STAFFNAME,COUNT(S.CID)
FROM STUDENT S
INNER JOIN STAFF E
ON S.CID = E.CID
GROUP BY E.STAFFNAME,S.CID
HAVING S.CID>1






SELECT * FROM  STAFF;
SELECT * FROM STUDENT;


SELECT E.STAFFNAME,COUNT(S.CID)
FROM STUDENT S
INNER JOIN STAFF E
ON S.CID = E.CID
GROUP BY E.STAFFNAME,S.CID
HAVING COUNT(S.CID)>1



--DISPLAY STAFFNAME , NO OF STUDENTS


SELECT E.STAFFNAME,COUNT(S.CID)
FROM STAFF E, STUDENT S
WHERE E.CID = S.CID
GROUP BY E.STAFFNAME,S.CID
HAVING COUNT(S.CID)>1



SELECT E.STAFFNAME,COUNT(S.CID)
FROM STAFF E, STUDENT S
WHERE E.CID = (SELECT CID FROM STUDENT 
				GROUP BY CID 
				HAVING COUNT(CID)>1)
GROUP BY E.STAFFNAME


SELECT * FROM STUDENT
DELETE FROM STUDENT WHERE ID = 8

INSERT INTO STUDENT VALUES (8,'HHHHHHHH',22)



SELECT E.STAFFNAME
FROM STAFF E, STUDENT S
WHERE E.CID IN (SELECT CID FROM STUDENT 
				GROUP BY CID 
				HAVING COUNT(CID)>1)
GROUP BY E.STAFFNAME

































































